# Generated by Django 4.2.13 on 2024-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_field_2_remove_post_field_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.SlugField(default='stink-stank-stunk'),
            preserve_default=False,
        ),
    ]
